services:
  grafana:
    # Container image with features
    # https://github.com/grafana/grafana/pull/114371
    # https://github.com/grafana/grafana/pull/114947
    image: docker.io/woozymasta/grafana:geomap-features
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - $PWD/grafana-data:/var/lib/grafana
      - $PWD/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - $PWD/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - $PWD/grafana/datasources.example.yml:/etc/grafana/provisioning/datasources/datasources.example.yml
