apiVersion: 1
datasources:
  - access: proxy
    basicAuth: true
    basicAuthUser: MyUser
    editable: true
    isDefault: false
    name: Prometheus
    secureJsonData:
      basicAuthPassword: MyPassword
    type: prometheus
    url: http://127.0.0.1:9090
